package org.devt.higherworld.world;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.EnumSet;
import java.util.Set;

/** Per-world selection of structures generated by HigherWorld below Y=-64. */
public final class StructureGenerationSettings {
    private static final String FILE_NAME = "structure_generation.json";
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
    private static EnumSet<UndergroundStructure> clientSelection = allStructures();
    private static EnumSet<UndergroundStructure> pendingWorldSelection;

    private final EnumSet<UndergroundStructure> enabled;

    private StructureGenerationSettings(Set<UndergroundStructure> enabled) {
        this.enabled = enabled.isEmpty()
                ? EnumSet.noneOf(UndergroundStructure.class)
                : EnumSet.copyOf(enabled);
    }

    public static StructureGenerationSettings defaults() {
        return new StructureGenerationSettings(allStructures());
    }

    public static StructureGenerationSettings none() {
        return new StructureGenerationSettings(EnumSet.noneOf(UndergroundStructure.class));
    }

    public boolean enables(UndergroundStructure structure) {
        return enabled.contains(structure);
    }

    public Set<UndergroundStructure> enabledStructures() {
        return Set.copyOf(enabled);
    }

    public static synchronized EnumSet<UndergroundStructure> clientSelection() {
        return clientSelection.clone();
    }

    public static synchronized void setClientSelection(Set<UndergroundStructure> selection) {
        clientSelection = selection.isEmpty()
                ? EnumSet.noneOf(UndergroundStructure.class)
                : EnumSet.copyOf(selection);
    }

    /** Called only when the Create World button actually starts world creation. */
    public static synchronized void markWorldCreationStarted() {
        pendingWorldSelection = clientSelection.clone();
    }

    static StructureGenerationSettings load(Path cubicRoot, boolean acceptPendingSelection) throws IOException {
        Path file = cubicRoot.resolve(FILE_NAME);
        if (Files.exists(file)) {
            return read(file);
        }

        EnumSet<UndergroundStructure> selected = allStructures();
        synchronized (StructureGenerationSettings.class) {
            if (acceptPendingSelection && pendingWorldSelection != null) {
                selected = pendingWorldSelection;
                pendingWorldSelection = null;
            }
        }
        StructureGenerationSettings settings = new StructureGenerationSettings(selected);
        if (acceptPendingSelection) {
            settings.write(file);
        }
        return settings;
    }

    private static StructureGenerationSettings read(Path file) throws IOException {
        try (Reader reader = Files.newBufferedReader(file)) {
            JsonObject root = JsonParser.parseReader(reader).getAsJsonObject();
            EnumSet<UndergroundStructure> selected = EnumSet.noneOf(UndergroundStructure.class);
            JsonArray entries = root.getAsJsonArray("enabled");
            if (entries != null) {
                entries.forEach(element -> {
                    UndergroundStructure structure = UndergroundStructure.byId(element.getAsString());
                    if (structure != null) {
                        selected.add(structure);
                    }
                });
            }
            return new StructureGenerationSettings(selected);
        } catch (RuntimeException exception) {
            throw new IOException("Invalid HigherWorld structure settings in " + file, exception);
        }
    }

    private void write(Path file) throws IOException {
        Files.createDirectories(file.getParent());
        JsonObject root = new JsonObject();
        root.addProperty("version", 1);
        JsonArray entries = new JsonArray();
        enabled.stream().map(UndergroundStructure::id).forEach(entries::add);
        root.add("enabled", entries);

        Path temporary = file.resolveSibling(file.getFileName() + ".tmp");
        try (Writer writer = Files.newBufferedWriter(temporary)) {
            GSON.toJson(root, writer);
        }
        try {
            Files.move(temporary, file, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
        } catch (java.nio.file.AtomicMoveNotSupportedException ignored) {
            Files.move(temporary, file, StandardCopyOption.REPLACE_EXISTING);
        }
    }

    private static EnumSet<UndergroundStructure> allStructures() {
        return EnumSet.allOf(UndergroundStructure.class);
    }
}
